runtime: python310
entrypoint: streamlit run app.py --server.port=$PORT --server.enableCORS=false

instance_class: F2

env_variables:
  GOOGLE_API_KEY: "AIzaSyC8MHjTSPaiFuCE53xtHHZHsUnfBM2eXr4"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2

handlers:
- url: /.*
  script: auto
